// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformyProgramistyczneAPI.F1Api;

#nullable disable

namespace PlatformyProgramistyczneAPI.Migrations
{
    [DbContext(typeof(DriversDatabase))]
    partial class DriversDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("PlatformyProgramistyczneAPI.F1Api.DriverDb", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("broadcast_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("country_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("driver_number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("headshot_url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("meeting_key")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name_acronym")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("session_key")
                        .HasColumnType("INTEGER");

                    b.Property<string>("team_colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("team_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            broadcast_name = "F GRZYWACZ",
                            country_code = "PL",
                            driver_number = 7,
                            first_name = "Filip",
                            full_name = "Filip Grzywacz",
                            headshot_url = "https://ecsmedia.pl/c/niepowstrzymany-w-iext132429663.jpg",
                            last_name = "Grzywacz",
                            meeting_key = 1219,
                            name_acronym = "GRZ",
                            session_key = 9158,
                            team_colour = "F91536",
                            team_name = "Ferrari"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
